CREATE TABLE IF NOT EXISTS worker (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    working_today BOOLEAN DEFAULT FALSE NOT NULL,
    CONSTRAINT uk_worker_full_name UNIQUE (first_name, last_name)
);

CREATE TABLE IF NOT EXISTS section_workers (
    section_id BIGINT NOT NULL,
    worker_id BIGINT NOT NULL,
    PRIMARY KEY (section_id, worker_id)
);

ALTER TABLE section DROP COLUMN IF EXISTS assigned_workers;

ALTER TABLE worker ADD COLUMN IF NOT EXISTS first_name VARCHAR(255);
ALTER TABLE worker ADD COLUMN IF NOT EXISTS last_name VARCHAR(255);
ALTER TABLE worker ADD COLUMN IF NOT EXISTS working_today BOOLEAN DEFAULT FALSE NOT NULL;

UPDATE worker SET first_name = 'Pracownik' WHERE first_name IS NULL;
UPDATE worker SET last_name = CAST(id AS VARCHAR) WHERE last_name IS NULL OR TRIM(last_name) = '';

ALTER TABLE worker DROP COLUMN IF EXISTS name;
